name: Run plugin tests

on: [pull_request]

jobs:

  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4', '8.0']
        wordpress-versions: ['5.3.0', 'latest']
        phpunit-versions: ['7.5.20', '9.5.26']
        exclude:
          - operating-system: ubuntu-latest
            php-versions: '8.0'
            wordpress-versions: '5.3.0'
            phpunit-versions: '7.5.20'
          - operating-system: ubuntu-latest
            php-versions: '8.0'
            wordpress-versions: '5.3.0'
            phpunit-versions: '9.5.26'
          - operating-system: ubuntu-latest
            php-versions: '7.4'
            wordpress-versions: '5.3.0'
            phpunit-versions: '9.5.26'
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    name: PHP ${{ matrix.php-versions }} with ${{ matrix.wordpress-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: mbstring, intl, mysql, mysqli
          ini-values-csv: post_max_size=256M, short_open_tag=On
          coverage: xdebug
          pecl: false
          tools: phpunit:${{ matrix.phpunit-versions }}

      - name: Install WP Tests
        run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:${{ job.services.mysql.ports['3306'] }} ${{ matrix.wordpress-versions }} true

      - name: Run phpunit tests
        run: phpunit

      - name: Run phpunit tests against multisite install
        run: WP_MULTISITE=1 phpunit

  phpcs:
    runs-on: ubuntu-latest
    name: Check WP Coding Standards
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '8.0'
          extension-csv: mbstring, intl
          ini-values-csv: post_max_size=256M, short_open_tag=On
          coverage: none
          pecl: false
          tools: phpcs

      - name: Setup PHPCS for WordPress
        run: |
          composer global require phpcompatibility/php-compatibility
          composer global require phpcompatibility/phpcompatibility-paragonie
          composer global require phpcompatibility/phpcompatibility-wp
          composer global require wp-coding-standards/wpcs
          composer global require automattic/vipwpcs
          composer global require dealerdirect/phpcodesniffer-composer-installer

      - name: Run PHPCS on the plugin
        run: phpcs

